### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by awolad** [juanjoDiaz/serverless-plugin-warmup#260]
![image](https://user-images.githubusercontent.com/9510958/115387889-11102280-a1fd-11eb-8693-af223a48aec1.png)

**Comment by quentinhayot** [comment]
I had the same issue when Serverless updated itself today at version 2.36.0
Rolling back to 2.35.0 fixes the issue for now.

**Comment by awolad** [comment]
Thanks, @quentinhayot you're correct.

**Comment by quentinhayot** [comment]
Here is the stacktrace in text format:
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
      at validateString (internal/validators.js:117:11)
      at Object.join (path.js:1039:7)
      at WarmUp.configureWarmer (/Users/quentinhayot/concilio/depots/cumulus/usagestats/node_modules/serverless-plugin-warmup/src/index.js:177:32)
      at /Users/quentinhayot/concilio/depots/cumulus/usagestats/node_modules/serverless-plugin-warmup/src/index.js:95:49
      at Array.map (<anonymous>)
      at WarmUp.initializeWarmers (/Users/quentinhayot/concilio/depots/cumulus/usagestats/node_modules/serverless-plugin-warmup/src/index.js:95:8)
      at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:552:20)
      at async PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:574:5)
      at async PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:552:9)
      at async PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:574:5)
      at async Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy.js:49:11)
      at async PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:552:9)
      at async PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:598:7)
      at async Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:312:5)
      at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:612:9
```
