### ISSUE TITLE
TypeError: Cannot destructure property 'log' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by coderkk1992** [juanjoDiaz/serverless-plugin-warmup#307]
Tried installing the plugin, but been getting this at the startup. any clue? 

```
TypeError: Cannot destructure property 'log' of 'undefined' as it is undefined.
      at new WarmUp (/Users/kalithk/Desktop/billion/backend/node_modules/serverless-plugin-warmup/src/index.js:33:41)
      at PluginManager.addPlugin (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:114:28)
      at /usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:160:33
      at Array.forEach (<anonymous>)
      at PluginManager.loadAllPlugins (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:160:8)
      at Serverless.init (/usr/local/lib/node_modules/serverless/lib/Serverless.js:213:30)
      at async /usr/local/lib/node_modules/serverless/scripts/serverless.js:583:7
```

**Comment by juanjoDiaz** [comment]
Yo are using the latest version of the plugin, which is compatible with Serverless 3.X, with Serverless 2.X.

Either update your serverless (recommended) or downgrade to v6.2.0 of this plugin.

**Comment by coderkk1992** [comment]
thanks @juanjoDiaz 👍  that worked.
